name: haplotyping
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - snakemake-minimal =7.0.1
  - r-base =4.0.2
  - r-stringr=1.4.0
  - mafft >= 7.505
  - emboss=6.6.0
  - bwa
  - seqkit >= 2.2.0
